### ISSUE TITLE
Figwheel never connects to browser

### ISSUE THREAD

**Issue by Engelberg** [reagent-project/reagent-template#128] opened 2016-12-20 01:05 UTC
```
lein new reagent myproject +test
cd myproject
lein figwheel

Figwheel: Cutting some fruit, just a sec ...
Figwheel: Validating the configuration found in project.clj
[32mFigwheel: Configuration Valid :)[0m
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - app
Figwheel: Cleaning build - app
[0mCompiling "target/cljsbuild/public/js/app.js" from ["src/cljs" "src/cljc" "env/dev/cljs"]...[0m
[32mSuccessfully compiled "target/cljsbuild/public/js/app.js" in 16.324 seconds.[0m
Figwheel: Starting CSS Watcher for paths  ["resources/public/css"]
Figwheel: Starting nREPL server on port: 7002
Launching ClojureScript REPL for build: app
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (print-config [id ...])         ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application
```

Then, in the browser I go to localhost:3449.
This serves up a page that when I view source looks like this:
```
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <div id="app">
    </div>
    <script src="js/testable.js" type="text/javascript"></script>
  </body>
</html>
```

The lein figwheel repl never starts.  Any idea what is going on here?  I'm running on Windows, although I don't see why that would make a difference in this case.  Thanks.

**Comment by Engelberg** [comment] 2016-12-20 01:45
It works if I create the project without the +test option.

**Comment by yogthos** [comment] 2016-12-20 23:56
Yeah, looks like there's a bug here. I'll try take a look when I get a chance.

**Comment by gadfly361** [comment] 2016-12-21 02:02
@yogthos I think if you remove doo from the dev dependencies vector the issue is resolved. Pushed a commit to [this branch](https://github.com/reagent-project/reagent-template/tree/issue-128).

**Comment by yogthos** [comment] 2016-12-21 03:09
Ah I see, sounds like there should be a separate test profile then.

**Comment by yogthos** [comment] 2016-12-21 03:42
@gadfly361 perfect, just merged and pushed out to Clojars

**Closed by yogthos** 2016-12-21 03:42 UTC
